
# https://hub.docker.com/repository/docker/gianlucavagnuzzi/tftp/tags

services:
  tftp:
    image: gianlucavagnuzzi/tftp
    container_name: tftp
    environment:
    - TZ=Europe/Rome
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/tftpboot:/var/tftpboot
    ports:
    - 69:69/udp
    restart: unless-stopped
